# Form implementation generated from reading ui file 'about_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about_dialog(object):
    def setupUi(self, about_dialog):
        about_dialog.setObjectName("about_dialog")
        about_dialog.resize(527, 326)
        self.grid_layout = QtWidgets.QGridLayout(about_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.license_group_box = QtWidgets.QGroupBox(parent=about_dialog)
        self.license_group_box.setTitle("")
        self.license_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.license_group_box.setObjectName("license_group_box")
        self.license_group_box_grid_layout = QtWidgets.QGridLayout(self.license_group_box)
        self.license_group_box_grid_layout.setObjectName("license_group_box_grid_layout")
        self.license_text_edit = QtWidgets.QTextEdit(parent=self.license_group_box)
        self.license_text_edit.setReadOnly(True)
        self.license_text_edit.setObjectName("license_text_edit")
        self.license_group_box_grid_layout.addWidget(self.license_text_edit, 1, 0, 1, 1)
        self.grid_layout.addWidget(self.license_group_box, 1, 0, 1, 3)
        self.about_label = QtWidgets.QLabel(parent=about_dialog)
        self.about_label.setObjectName("about_label")
        self.grid_layout.addWidget(self.about_label, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=about_dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 4, 0, 1, 3)

        self.retranslateUi(about_dialog)
        self.button_box.accepted.connect(about_dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(about_dialog)

    def retranslateUi(self, about_dialog):
        _translate = QtCore.QCoreApplication.translate
        about_dialog.setWindowTitle(_translate("about_dialog", "关于 CipherManagerGUI"))
        self.about_label.setText(_translate("about_dialog", "CipherManagerGUI"))
