# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about_form(object):
    def setupUi(self, about_form):
        about_form.setObjectName("about_form")
        about_form.resize(432, 326)
        about_form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.grid_layout = QtWidgets.QGridLayout(about_form)
        self.grid_layout.setObjectName("grid_layout")
        spacerItem = QtWidgets.QSpacerItem(161, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem1, 2, 2, 2, 1)
        self.license_group_box = QtWidgets.QGroupBox(about_form)
        self.license_group_box.setTitle("")
        self.license_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.license_group_box.setObjectName("license_group_box")
        self.license_group_box_grid_layout = QtWidgets.QGridLayout(self.license_group_box)
        self.license_group_box_grid_layout.setObjectName("license_group_box_grid_layout")
        self.license_plain_text_edit = QtWidgets.QPlainTextEdit(self.license_group_box)
        self.license_plain_text_edit.setReadOnly(True)
        self.license_plain_text_edit.setObjectName("license_plain_text_edit")
        self.license_group_box_grid_layout.addWidget(self.license_plain_text_edit, 1, 0, 1, 1)
        self.grid_layout.addWidget(self.license_group_box, 1, 0, 1, 3)
        self.ok_push_button = QtWidgets.QPushButton(about_form)
        self.ok_push_button.setObjectName("ok_push_button")
        self.grid_layout.addWidget(self.ok_push_button, 3, 1, 1, 1)
        self.about_label = QtWidgets.QLabel(about_form)
        self.about_label.setObjectName("about_label")
        self.grid_layout.addWidget(self.about_label, 0, 0, 1, 1)

        self.retranslateUi(about_form)
        self.ok_push_button.clicked.connect(about_form.close)
        QtCore.QMetaObject.connectSlotsByName(about_form)

    def retranslateUi(self, about_form):
        _translate = QtCore.QCoreApplication.translate
        about_form.setWindowTitle(_translate("about_form", "关于 CipherManagerGUI"))
        self.ok_push_button.setText(_translate("about_form", "OK"))
        self.about_label.setText(_translate("about_form", "CipherManagerGUI"))
