# Form implementation generated from reading ui file 'attribute_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_attribute_dialog(object):
    def setupUi(self, attribute_dialog):
        attribute_dialog.setObjectName("attribute_dialog")
        attribute_dialog.resize(633, 444)
        self.grid_layout = QtWidgets.QGridLayout(attribute_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.attribute_tab_widget = QtWidgets.QTabWidget(parent=attribute_dialog)
        self.attribute_tab_widget.setObjectName("attribute_tab_widget")
        self.formatted = QtWidgets.QWidget()
        self.formatted.setObjectName("formatted")
        self.formatted_grid_layout = QtWidgets.QGridLayout(self.formatted)
        self.formatted_grid_layout.setObjectName("formatted_grid_layout")
        self.attribute_tree_view = QtWidgets.QTreeView(parent=self.formatted)
        self.attribute_tree_view.setObjectName("attribute_tree_view")
        self.formatted_grid_layout.addWidget(self.attribute_tree_view, 0, 0, 1, 1)
        self.attribute_tab_widget.addTab(self.formatted, "")
        self.raw_data = QtWidgets.QWidget()
        self.raw_data.setObjectName("raw_data")
        self.raw_data_grid_layout = QtWidgets.QGridLayout(self.raw_data)
        self.raw_data_grid_layout.setObjectName("raw_data_grid_layout")
        self.raw_data_text_edit = QtWidgets.QTextEdit(parent=self.raw_data)
        self.raw_data_text_edit.setReadOnly(True)
        self.raw_data_text_edit.setObjectName("raw_data_text_edit")
        self.raw_data_grid_layout.addWidget(self.raw_data_text_edit, 0, 0, 1, 1)
        self.attribute_tab_widget.addTab(self.raw_data, "")
        self.grid_layout.addWidget(self.attribute_tab_widget, 2, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=attribute_dialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 3, 0, 1, 1)

        self.retranslateUi(attribute_dialog)
        self.attribute_tab_widget.setCurrentIndex(0)
        self.button_box.accepted.connect(attribute_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(attribute_dialog)

    def retranslateUi(self, attribute_dialog):
        _translate = QtCore.QCoreApplication.translate
        attribute_dialog.setWindowTitle(_translate("attribute_dialog", "属性"))
        self.attribute_tab_widget.setTabText(self.attribute_tab_widget.indexOf(self.formatted), _translate("attribute_dialog", "格式化"))
        self.attribute_tab_widget.setTabText(self.attribute_tab_widget.indexOf(self.raw_data), _translate("attribute_dialog", "原始数据"))
