# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attribute_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeDialog(object):
    def setupUi(self, AttributeDialog):
        AttributeDialog.setObjectName("AttributeDialog")
        AttributeDialog.resize(633, 444)
        self.gridLayout = QtWidgets.QGridLayout(AttributeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.attribute_tree_view = QtWidgets.QTreeView(AttributeDialog)
        self.attribute_tree_view.setObjectName("attribute_tree_view")
        self.gridLayout.addWidget(self.attribute_tree_view, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AttributeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(AttributeDialog)
        self.buttonBox.accepted.connect(AttributeDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AttributeDialog)

    def retranslateUi(self, AttributeDialog):
        _translate = QtCore.QCoreApplication.translate
        AttributeDialog.setWindowTitle(_translate("AttributeDialog", "Dialog"))
