# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attribute_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_attribute_dialog(object):
    def setupUi(self, attribute_dialog):
        attribute_dialog.setObjectName("attribute_dialog")
        attribute_dialog.resize(633, 444)
        self.grid_layout = QtWidgets.QGridLayout(attribute_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.attribute_tree_view = QtWidgets.QTreeView(attribute_dialog)
        self.attribute_tree_view.setObjectName("attribute_tree_view")
        self.grid_layout.addWidget(self.attribute_tree_view, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(attribute_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 1, 0, 1, 1)

        self.retranslateUi(attribute_dialog)
        self.button_box.accepted.connect(attribute_dialog.close)
        QtCore.QMetaObject.connectSlotsByName(attribute_dialog)

    def retranslateUi(self, attribute_dialog):
        _translate = QtCore.QCoreApplication.translate
        attribute_dialog.setWindowTitle(_translate("attribute_dialog", "属性"))
