# Form implementation generated from reading ui file 'delayed_operation_confirm_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_delayed_operation_confirm_dialog(object):
    def setupUi(self, delayed_operation_confirm_dialog):
        delayed_operation_confirm_dialog.setObjectName("delayed_operation_confirm_dialog")
        delayed_operation_confirm_dialog.resize(336, 144)
        self.grid_layout = QtWidgets.QGridLayout(delayed_operation_confirm_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.label = QtWidgets.QLabel(parent=delayed_operation_confirm_dialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter|QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.grid_layout.addWidget(self.label, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=delayed_operation_confirm_dialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 2, 0, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(parent=delayed_operation_confirm_dialog)
        self.progress_bar.setProperty("value", 100)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.grid_layout.addWidget(self.progress_bar, 1, 0, 1, 1)

        self.retranslateUi(delayed_operation_confirm_dialog)
        self.button_box.accepted.connect(delayed_operation_confirm_dialog.accept) # type: ignore
        self.button_box.rejected.connect(delayed_operation_confirm_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(delayed_operation_confirm_dialog)

    def retranslateUi(self, delayed_operation_confirm_dialog):
        _translate = QtCore.QCoreApplication.translate
        delayed_operation_confirm_dialog.setWindowTitle(_translate("delayed_operation_confirm_dialog", "将执行操作"))
        self.label.setText(_translate("delayed_operation_confirm_dialog", "将执行操作"))
