# Form implementation generated from reading ui file 'image_show_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_image_show_dialog(object):
    def setupUi(self, image_show_dialog):
        image_show_dialog.setObjectName("image_show_dialog")
        image_show_dialog.resize(400, 300)
        self.grid_layout = QtWidgets.QGridLayout(image_show_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.button_box = QtWidgets.QDialogButtonBox(parent=image_show_dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 1, 0, 1, 1)
        self.image_label = QtWidgets.QLabel(parent=image_show_dialog)
        self.image_label.setText("")
        self.image_label.setScaledContents(True)
        self.image_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.grid_layout.addWidget(self.image_label, 0, 0, 1, 1)

        self.retranslateUi(image_show_dialog)
        self.button_box.accepted.connect(image_show_dialog.accept) # type: ignore
        self.button_box.rejected.connect(image_show_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(image_show_dialog)

    def retranslateUi(self, image_show_dialog):
        _translate = QtCore.QCoreApplication.translate
        image_show_dialog.setWindowTitle(_translate("image_show_dialog", "Dialog"))
