# Form implementation generated from reading ui file 'input_password_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InputPasswordDialog(object):
    def setupUi(self, InputPasswordDialog):
        InputPasswordDialog.setObjectName("InputPasswordDialog")
        InputPasswordDialog.resize(401, 313)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputPasswordDialog.sizePolicy().hasHeightForWidth())
        InputPasswordDialog.setSizePolicy(sizePolicy)
        self.grid_layout = QtWidgets.QGridLayout(InputPasswordDialog)
        self.grid_layout.setObjectName("grid_layout")
        self.show_password_check_box = QtWidgets.QCheckBox(parent=InputPasswordDialog)
        self.show_password_check_box.setObjectName("show_password_check_box")
        self.grid_layout.addWidget(self.show_password_check_box, 2, 1, 1, 1)
        self.password_encoding_label = QtWidgets.QLabel(parent=InputPasswordDialog)
        self.password_encoding_label.setObjectName("password_encoding_label")
        self.grid_layout.addWidget(self.password_encoding_label, 2, 3, 1, 1)
        self.multi_line_check_box = QtWidgets.QCheckBox(parent=InputPasswordDialog)
        self.multi_line_check_box.setObjectName("multi_line_check_box")
        self.grid_layout.addWidget(self.multi_line_check_box, 2, 2, 1, 1)
        self.error_label = QtWidgets.QLabel(parent=InputPasswordDialog)
        self.error_label.setObjectName("error_label")
        self.grid_layout.addWidget(self.error_label, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.grid_layout.addItem(spacerItem, 2, 0, 1, 1)
        self.password_encoding_combo_box = QtWidgets.QComboBox(parent=InputPasswordDialog)
        self.password_encoding_combo_box.setEditable(True)
        self.password_encoding_combo_box.setObjectName("password_encoding_combo_box")
        self.grid_layout.addWidget(self.password_encoding_combo_box, 2, 4, 1, 1)
        self.plain_text_edit = QtWidgets.QPlainTextEdit(parent=InputPasswordDialog)
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.grid_layout.addWidget(self.plain_text_edit, 1, 0, 1, 5)
        self.line_edit = QtWidgets.QLineEdit(parent=InputPasswordDialog)
        self.line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_edit.setObjectName("line_edit")
        self.grid_layout.addWidget(self.line_edit, 0, 0, 1, 5)
        self.button_box = QtWidgets.QDialogButtonBox(parent=InputPasswordDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 4, 0, 1, 5)

        self.retranslateUi(InputPasswordDialog)
        self.button_box.accepted.connect(InputPasswordDialog.accept) # type: ignore
        self.button_box.rejected.connect(InputPasswordDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InputPasswordDialog)

    def retranslateUi(self, InputPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        InputPasswordDialog.setWindowTitle(_translate("InputPasswordDialog", "输入密码"))
        self.show_password_check_box.setText(_translate("InputPasswordDialog", "显示密码"))
        self.password_encoding_label.setText(_translate("InputPasswordDialog", "密码编码格式："))
        self.multi_line_check_box.setText(_translate("InputPasswordDialog", "多行密码"))
