# Form implementation generated from reading ui file 'input_password_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InputPasswordDialog(object):
    def setupUi(self, InputPasswordDialog):
        InputPasswordDialog.setObjectName("InputPasswordDialog")
        InputPasswordDialog.resize(338, 81)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputPasswordDialog.sizePolicy().hasHeightForWidth())
        InputPasswordDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(InputPasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=InputPasswordDialog)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=InputPasswordDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(InputPasswordDialog)
        self.buttonBox.accepted.connect(InputPasswordDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InputPasswordDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InputPasswordDialog)

    def retranslateUi(self, InputPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        InputPasswordDialog.setWindowTitle(_translate("InputPasswordDialog", "输入密码"))
