# Form implementation generated from reading ui file 'new_cipher_file_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewCipherFileDialog(object):
    def setupUi(self, NewCipherFileDialog):
        NewCipherFileDialog.setObjectName("NewCipherFileDialog")
        NewCipherFileDialog.resize(609, 375)
        self.gridLayout = QtWidgets.QGridLayout(NewCipherFileDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.encoding_combo_box = QtWidgets.QComboBox(parent=NewCipherFileDialog)
        self.encoding_combo_box.setEditable(True)
        self.encoding_combo_box.setObjectName("encoding_combo_box")
        self.gridLayout.addWidget(self.encoding_combo_box, 0, 2, 1, 1)
        self.encoding_label = QtWidgets.QLabel(parent=NewCipherFileDialog)
        self.encoding_label.setObjectName("encoding_label")
        self.gridLayout.addWidget(self.encoding_label, 0, 1, 1, 1)
        self.cipher_type_list_widget = QtWidgets.QListWidget(parent=NewCipherFileDialog)
        self.cipher_type_list_widget.setObjectName("cipher_type_list_widget")
        self.gridLayout.addWidget(self.cipher_type_list_widget, 0, 0, 2, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=NewCipherFileDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 327, 297))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cipher_grid_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.cipher_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.cipher_grid_layout.setObjectName("cipher_grid_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 1, 3)
        self.current_location_encoding_push_button = QtWidgets.QPushButton(parent=NewCipherFileDialog)
        self.current_location_encoding_push_button.setObjectName("current_location_encoding_push_button")
        self.gridLayout.addWidget(self.current_location_encoding_push_button, 0, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewCipherFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(NewCipherFileDialog)
        self.buttonBox.accepted.connect(NewCipherFileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewCipherFileDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewCipherFileDialog)

    def retranslateUi(self, NewCipherFileDialog):
        _translate = QtCore.QCoreApplication.translate
        NewCipherFileDialog.setWindowTitle(_translate("NewCipherFileDialog", "新建"))
        self.encoding_label.setText(_translate("NewCipherFileDialog", "字符编码："))
        self.current_location_encoding_push_button.setText(_translate("NewCipherFileDialog", "当前区域"))
