# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_cipher_file_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCipherFileDialog(object):
    def setupUi(self, NewCipherFileDialog):
        NewCipherFileDialog.setObjectName("NewCipherFileDialog")
        NewCipherFileDialog.resize(609, 375)
        self.gridLayout = QtWidgets.QGridLayout(NewCipherFileDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.cipher_type_list_widget = QtWidgets.QListWidget(NewCipherFileDialog)
        self.cipher_type_list_widget.setObjectName("cipher_type_list_widget")
        self.gridLayout.addWidget(self.cipher_type_list_widget, 0, 0, 3, 1)
        self.encoding_label = QtWidgets.QLabel(NewCipherFileDialog)
        self.encoding_label.setObjectName("encoding_label")
        self.gridLayout.addWidget(self.encoding_label, 0, 1, 1, 1)
        self.encoding_combo_box = QtWidgets.QComboBox(NewCipherFileDialog)
        self.encoding_combo_box.setEditable(True)
        self.encoding_combo_box.setObjectName("encoding_combo_box")
        self.gridLayout.addWidget(self.encoding_combo_box, 0, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(NewCipherFileDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 322, 288))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.cipher_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.cipher_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.cipher_grid_layout.setObjectName("cipher_grid_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewCipherFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(NewCipherFileDialog)
        self.buttonBox.accepted.connect(NewCipherFileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewCipherFileDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewCipherFileDialog)

    def retranslateUi(self, NewCipherFileDialog):
        _translate = QtCore.QCoreApplication.translate
        NewCipherFileDialog.setWindowTitle(_translate("NewCipherFileDialog", "新建"))
        self.encoding_label.setText(_translate("NewCipherFileDialog", "字符编码："))
