# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'random_password_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomPasswordDialog(object):
    def setupUi(self, RandomPasswordDialog):
        RandomPasswordDialog.setObjectName("RandomPasswordDialog")
        RandomPasswordDialog.resize(400, 160)
        self.gridLayout = QtWidgets.QGridLayout(RandomPasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.length_label = QtWidgets.QLabel(RandomPasswordDialog)
        self.length_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.length_label.setObjectName("length_label")
        self.gridLayout.addWidget(self.length_label, 1, 0, 1, 1)
        self.length_spin_box = QtWidgets.QSpinBox(RandomPasswordDialog)
        self.length_spin_box.setMinimum(16)
        self.length_spin_box.setMaximum(65535)
        self.length_spin_box.setObjectName("length_spin_box")
        self.gridLayout.addWidget(self.length_spin_box, 1, 1, 1, 1)
        self.spawn_push_button = QtWidgets.QPushButton(RandomPasswordDialog)
        self.spawn_push_button.setObjectName("spawn_push_button")
        self.gridLayout.addWidget(self.spawn_push_button, 1, 2, 1, 1)
        self.import_condition_push_button = QtWidgets.QPushButton(RandomPasswordDialog)
        self.import_condition_push_button.setObjectName("import_condition_push_button")
        self.gridLayout.addWidget(self.import_condition_push_button, 0, 2, 1, 1)
        self.character_set_label = QtWidgets.QLabel(RandomPasswordDialog)
        self.character_set_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.character_set_label.setObjectName("character_set_label")
        self.gridLayout.addWidget(self.character_set_label, 0, 0, 1, 1)
        self.character_set_combo_box = QtWidgets.QComboBox(RandomPasswordDialog)
        self.character_set_combo_box.setObjectName("character_set_combo_box")
        self.gridLayout.addWidget(self.character_set_combo_box, 0, 1, 1, 1)
        self.result_plain_text_edit = QtWidgets.QPlainTextEdit(RandomPasswordDialog)
        self.result_plain_text_edit.setReadOnly(True)
        self.result_plain_text_edit.setObjectName("result_plain_text_edit")
        self.gridLayout.addWidget(self.result_plain_text_edit, 3, 2, 1, 1)
        self.condition_label = QtWidgets.QLabel(RandomPasswordDialog)
        self.condition_label.setObjectName("condition_label")
        self.gridLayout.addWidget(self.condition_label, 3, 0, 1, 1)
        self.condition_list_widget = QtWidgets.QListWidget(RandomPasswordDialog)
        self.condition_list_widget.setObjectName("condition_list_widget")
        self.gridLayout.addWidget(self.condition_list_widget, 3, 1, 2, 1)

        self.retranslateUi(RandomPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(RandomPasswordDialog)

    def retranslateUi(self, RandomPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        RandomPasswordDialog.setWindowTitle(_translate("RandomPasswordDialog", "随机生成口令"))
        self.length_label.setText(_translate("RandomPasswordDialog", "口令长度："))
        self.spawn_push_button.setText(_translate("RandomPasswordDialog", "生成口令"))
        self.import_condition_push_button.setText(_translate("RandomPasswordDialog", "导入规则"))
        self.character_set_label.setText(_translate("RandomPasswordDialog", "字符集："))
        self.result_plain_text_edit.setPlaceholderText(_translate("RandomPasswordDialog", "无结果"))
        self.condition_label.setText(_translate("RandomPasswordDialog", "条件："))
