# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'random_password_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomPasswordDialog(object):
    def setupUi(self, RandomPasswordDialog):
        RandomPasswordDialog.setObjectName("RandomPasswordDialog")
        RandomPasswordDialog.resize(400, 306)
        self.gridLayout = QtWidgets.QGridLayout(RandomPasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_of_length = QtWidgets.QLabel(RandomPasswordDialog)
        self.label_of_length.setObjectName("label_of_length")
        self.gridLayout.addWidget(self.label_of_length, 0, 0, 1, 1)
        self.spin_box_of_length = QtWidgets.QSpinBox(RandomPasswordDialog)
        self.spin_box_of_length.setMinimum(16)
        self.spin_box_of_length.setMaximum(65535)
        self.spin_box_of_length.setObjectName("spin_box_of_length")
        self.gridLayout.addWidget(self.spin_box_of_length, 0, 1, 1, 2)
        self.list_view_of_condition = QtWidgets.QListView(RandomPasswordDialog)
        self.list_view_of_condition.setObjectName("list_view_of_condition")
        self.gridLayout.addWidget(self.list_view_of_condition, 1, 1, 1, 4)
        self.label_of_add_condition = QtWidgets.QLabel(RandomPasswordDialog)
        self.label_of_add_condition.setObjectName("label_of_add_condition")
        self.gridLayout.addWidget(self.label_of_add_condition, 4, 0, 1, 2)
        self.line_edit_of_add_condition = QtWidgets.QLineEdit(RandomPasswordDialog)
        self.line_edit_of_add_condition.setObjectName("line_edit_of_add_condition")
        self.gridLayout.addWidget(self.line_edit_of_add_condition, 4, 2, 1, 2)
        self.push_button_of_add_condition = QtWidgets.QPushButton(RandomPasswordDialog)
        self.push_button_of_add_condition.setObjectName("push_button_of_add_condition")
        self.gridLayout.addWidget(self.push_button_of_add_condition, 4, 4, 1, 1)
        self.push_button_of_spawn = QtWidgets.QPushButton(RandomPasswordDialog)
        self.push_button_of_spawn.setObjectName("push_button_of_spawn")
        self.gridLayout.addWidget(self.push_button_of_spawn, 5, 3, 1, 2)
        self.plain_text_edit_of_result = QtWidgets.QPlainTextEdit(RandomPasswordDialog)
        self.plain_text_edit_of_result.setReadOnly(True)
        self.plain_text_edit_of_result.setObjectName("plain_text_edit_of_result")
        self.gridLayout.addWidget(self.plain_text_edit_of_result, 6, 0, 1, 5)
        self.label_of_condition = QtWidgets.QLabel(RandomPasswordDialog)
        self.label_of_condition.setObjectName("label_of_condition")
        self.gridLayout.addWidget(self.label_of_condition, 1, 0, 1, 1)

        self.retranslateUi(RandomPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(RandomPasswordDialog)

    def retranslateUi(self, RandomPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        RandomPasswordDialog.setWindowTitle(_translate("RandomPasswordDialog", "随机生成密码"))
        self.label_of_length.setText(_translate("RandomPasswordDialog", "长度："))
        self.label_of_add_condition.setText(_translate("RandomPasswordDialog", "添加规则："))
        self.line_edit_of_add_condition.setPlaceholderText(_translate("RandomPasswordDialog", "请输入有效的正则表达式"))
        self.push_button_of_add_condition.setText(_translate("RandomPasswordDialog", "添加"))
        self.push_button_of_spawn.setText(_translate("RandomPasswordDialog", "生成密码"))
        self.label_of_condition.setText(_translate("RandomPasswordDialog", "规则："))
