# Form implementation generated from reading ui file 'table_view_show_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_table_view_show_dialog(object):
    def setupUi(self, table_view_show_dialog):
        table_view_show_dialog.setObjectName("table_view_show_dialog")
        table_view_show_dialog.resize(400, 300)
        self.grid_layout = QtWidgets.QGridLayout(table_view_show_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.button_box = QtWidgets.QDialogButtonBox(parent=table_view_show_dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 1, 0, 1, 1)
        self.table_view = QtWidgets.QTableView(parent=table_view_show_dialog)
        self.table_view.setObjectName("table_view")
        self.grid_layout.addWidget(self.table_view, 0, 0, 1, 1)

        self.retranslateUi(table_view_show_dialog)
        self.button_box.accepted.connect(table_view_show_dialog.accept) # type: ignore
        self.button_box.rejected.connect(table_view_show_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(table_view_show_dialog)

    def retranslateUi(self, table_view_show_dialog):
        _translate = QtCore.QCoreApplication.translate
        table_view_show_dialog.setWindowTitle(_translate("table_view_show_dialog", "Dialog"))
