# Form implementation generated from reading ui file 'text_show_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_text_show_dialog(object):
    def setupUi(self, text_show_dialog):
        text_show_dialog.setObjectName("text_show_dialog")
        text_show_dialog.resize(400, 300)
        text_show_dialog.setWindowTitle("")
        self.grid_layout = QtWidgets.QGridLayout(text_show_dialog)
        self.grid_layout.setObjectName("grid_layout")
        self.plain_text_edit = QtWidgets.QPlainTextEdit(parent=text_show_dialog)
        self.plain_text_edit.setReadOnly(True)
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.grid_layout.addWidget(self.plain_text_edit, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(parent=text_show_dialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.grid_layout.addWidget(self.button_box, 1, 0, 1, 1)

        self.retranslateUi(text_show_dialog)
        self.button_box.accepted.connect(text_show_dialog.accept) # type: ignore
        self.button_box.rejected.connect(text_show_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(text_show_dialog)

    def retranslateUi(self, text_show_dialog):
        pass
